name: YAML validation

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ master, devel ]

jobs:
  yaml-validation:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: YAML Lint
      uses: ibiqlik/action-yamllint@v1.0.0
      with:
        ## File(s) or Directory, separate by space if multiple files or folder are specified
        file_or_dir: model/
        ## Custom configuration (as YAML source)
        config_data: "{extends: default, rules: {line-length: disable}}"
        ## Return non-zero exit code on warnings as well as errors
        # strict: # optional, default is false

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Test import with cobrapy and consistency with annotation files
      run: |
        pip install cobra
        python code/test/basicCheck.py
